### ISSUE TITLE
Release weatherOz 1.0.0

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/weatherOz#67]
First release:

* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#sec-code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `urlchecker::url_check()`
* [x] `devtools::build_readme()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check()`, see <https://github.com/ropensci/weatherOz/actions/runs/8748608983>

Submit to CRAN:

* [ ] `devtools::release()`
* [ ] Approve email

Wait for CRAN...

* [ ] Accepted :tada:
* [ ] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version(push = TRUE)`
* [ ] Tweet

**Comment by adamhsparks** [comment]
Setting up the release issue only, @bozaah. 

Please do this when you get the time. My suggestion is get it accepted to CRAN and then we publish it in JOSS in that order so I've updated the `paper` branch so we can have a clean PR once this is all finalised.

**Comment by bozaah** [comment]
One issue I am unsure how we address is the `urlchecker::url_check()` and `rhub::check()` errors given the lack of https certificate in the Bureau website. Any ideas?

**Comment by adamhsparks** [comment]
yeah, I've had a discussion in the rOpenSci Slack Package Maintenance channel about this very topic that you can look at.

I'm of two minds. One is to just remove them as BOM could change the URL any day and we'd not be able to track it easily. The other is, BOM hasn't changed those URLs in years, so we can just include a note in the cran-comments.md to that effect that BOM won't allow headless access, but that we've verified they work and BOM is very unlikely to change the URLs.

**Comment by adamhsparks** [comment]
OK, I think it's really ready now. I've done all the checks, it passes everything as far as I can tell. I've included a note in cran-comments.md about the BOM URLs and updated all others that were reported as moved or incorrect.

I've submitted one last check to Winbuilder just to be sure.

**Comment by adamhsparks** [comment]
Seems passing winbuilder checks now. I think it's good to submit to CRAN now that the paper is accepted @bozaah

**Comment by adamhsparks** [comment]
This is now on CRAN, closing this issue
