### ISSUE TITLE
Average wind speed data from weatherOz

### ISSUE THREAD

**Issue by alycest** [ropensci/weatherOz#82]
Average wind speed data extracted using get_dpird_summaries is ranked from lowest to highest and does not match the observation recorded at that time. This is evident for 15-minute, 30-minute, hourly, daily, and yearly data summaries. However, the stats (avg, min, max) reflect the observation.

eg
get_dpird_summaries(
        station_code = "PI001",
        start_date = 20230101,
        end_date = 20240101,
        api_key = local_api_key,
        interval = "hourly",
        values = "wind")

Refer to attached plots as an example.    
[avg_windspd_2023.pdf](https://github.com/user-attachments/files/16408517/avg_windspd_2023.pdf)

R version 4.4.0 

@bozaah

**Comment by adamhsparks** [comment]
@bozaah, I have an idea where this is occurring. It's likely due to how I handled the 3 and 10m wind measurements and then recombined everything. I'll see what I can find. Same goes for wind direction.
