### ISSUE TITLE
Average wind direction data from weatherOz

### ISSUE THREAD

**Issue by alycest** [ropensci/weatherOz#83]
Average wind direction data extracted using get_dpird_summaries do not match the observation average wind direction recorded at that time. This is evident for 15-minute, 30-minute, hourly, daily, and yearly data summaries. 

eg
get_dpird_summaries(
station_code = "PI001",
start_date = 20230101,
end_date = 20240101,
api_key = local_api_key,
interval = "hourly",
values = "wind")

Refer to attached plots as an example. Green is wind direction data pulled from weatherOz, blue is data downloaded from DPIRD's WeatherAdmin
[avg_winddir_2023.pdf](https://github.com/user-attachments/files/16408690/avg_winddir_2023.pdf)

R version 4.4.0

@bozaah

**Comment by adamhsparks** [comment]
Hi @alycest, thank you for reporting these issues. I believe that I had found and fixed them. Could you please test with the version available from GitHub for me?

**Comment by alycest** [comment]
Thank @adamhsparks, issue has been resolved and extracting the observed data! Cheers 
[avg_windspd_2023.pdf](https://github.com/user-attachments/files/16489775/avg_windspd_2023.pdf)

[avg_winddir_2023.pdf](https://github.com/user-attachments/files/16489773/avg_winddir_2023.pdf)
